name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.15'

    - name: Install dependencies
      run: npm install

    - name: Ensure environments directory exists
      run: mkdir -p src/environments

    - name: Generate empty environment.ts
      run: echo "" > src/environments/environment.ts
      
    - name: Generate environment.prod.ts
      run: |
        echo "export const environment = {" > src/environments/environment.prod.ts
        echo "  production: true," >> src/environments/environment.prod.ts
        echo "  firebase: {" >> src/environments/environment.prod.ts
        echo "    apiKey: '${{ secrets.API_KEY }}'," >> src/environments/environment.prod.ts
        echo "    authDomain: '${{ secrets.AUTH_DOMAIN }}'," >> src/environments/environment.prod.ts
        echo "    projectId: '${{ secrets.PROJECT_ID }}'," >> src/environments/environment.prod.ts
        echo "    storageBucket: '${{ secrets.STORAGE_BUCKET }}'," >> src/environments/environment.prod.ts
        echo "    messagingSenderId: '${{ secrets.MESSAGING_SENDER_ID }}'," >> src/environments/environment.prod.ts
        echo "    appId: '${{ secrets.APP_ID }}'" >> src/environments/environment.prod.ts
        echo "  }" >> src/environments/environment.prod.ts
        echo "};" >> src/environments/environment.prod.ts

    - name: Build Angular project
      run: npm run build --prod

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting
